/**
 * Libellés de la quatrième partie du canevas RÉGIONAL — santé animale,
 * inspection et contrôle sanitaire.
 *
 * EXTRAITS AUTOMATIQUEMENT du .docx de la DREPIA-Ouest par
 * scripts/extraire-libelles-sante.mjs, et non retapés : certaines de ces
 * listes comptent près de soixante entrées, où la moindre faute de frappe
 * passerait inaperçue.
 *
 * Les noms de départements et les lignes de total en sont exclus : ils
 * relèvent de l'adaptation départementale, pas du contenu du canevas.
 */

/** 14 entrées, tableau régional #114. */
export const VACCINATION_AFFECTIONS: string[] = [
  "PPCB",
  "PPR",
  "Rouget",
  "MNC",
  "Variole aviaire",
  "Maladie de Gumboro",
  "Bronchite infectieuse",
  "Rage canine",
  "CharbonSymptomatique",
  "Maladie nodulaire",
  "Pasteurellose",
  "Cholera",
  "Colibacillose",
  "Parvovirose",
];

/** 21 entrées, tableau régional #116. */
export const SEMAINES_EPIDEMIOLOGIQUES: string[] = [
  "SE03",
  "SE05",
  "SE07",
  "SE08",
  "SE09",
  "SE11",
  "SE11",
  "SE12",
  "SE13",
  "SE17",
  "SE21",
  "SE22",
  "SE23",
  "SE24",
  "SE25",
  "SE29",
  "SE33",
  "SE35",
  "SE38",
  "SE46",
  "SE48",
];

/** 11 entrées, tableau régional #118. */
export const ESPECES_CONSULTATIONS: string[] = [
  "Bovine",
  "Ovine",
  "Caprine",
  "Porcine",
  "Equine",
  "Canine",
  "Féline",
  "Volaille",
  "Lapin",
  "Caille",
  "Autres",
];

/** 11 entrées, tableau régional #119. */
export const ESPECES_DEPARASITAGES: string[] = [
  "Bovine",
  "Ovine",
  "Caprine",
  "Porcine",
  "Equine",
  "Canine",
  "Féline",
  "Volaille",
  "Lapine",
  "Caille",
  "Autres",
];

/** 6 entrées, tableau régional #120. */
export const ESPECES_CASTRATIONS: string[] = [
  "Bovine",
  "Ovine",
  "Caprine",
  "Porcine",
  "Equine",
  "Canine",
];

/** 59 entrées, tableau régional #121. */
export const AFFECTIONS_RECURRENTES: string[] = [
  "Abcès",
  "Affection cutanée",
  "Agalactie",
  "Anémie",
  "Arthrite",
  "Ascaridioses",
  "Avitaminoses",
  "Avortements",
  "Boiterie",
  "Bronchites",
  "Coccidiose aviaire",
  "Colibacilloses",
  "Coliques",
  "Constipation",
  "Dermatose",
  "Dépilation",
  "Diarrhée",
  "Distomatoses",
  "Dystocie",
  "Ectoparasitoses",
  "Eczéma",
  "Emphysème",
  "Endoparasitoses",
  "Fièvre aphteuse",
  "Fractures",
  "Gale",
  "Gastro entérite",
  "Helminthoses",
  "Hématomes",
  "Hernie",
  "Kérato-conjonctivite",
  "Kyste",
  "Maladie de carré",
  "Maladies rouges du porc",
  "Maladies de New Castle",
  "Mammites",
  "Mastite",
  "Métrite",
  "Myiase",
  "Oestroses",
  "Orchite",
  "Otite",
  "Parvovirose",
  "Pasteurelloses",
  "Piétin",
  "Piroplasmoses",
  "Plaie",
  "Péricardite",
  "Pneumonie",
  "Polype",
  "PPR",
  "Rétentions placentaires",
  "Sarcoma de striker",
  "Salmonelloses",
  "Steptothricoses",
  "Splénomégalie",
  "Stress",
  "Tuberculose",
  "Toux",
];

/** 7 entrées, tableau régional #124. */
export const ESPECES_ABATTAGES_INSPECTION: string[] = [
  "Bovins",
  "Ovins",
  "Caprins",
  "Porcins",
  "Equins",
  "Volaille",
  "Asins",
];

/** 33 entrées, tableau régional #125. */
export const LESIONS_DECELEES: string[] = [
  "Avitaminoses",
  "Abcès divers",
  "Affections cutanées",
  "Boiterie",
  "Cysticercose",
  "Echinococcose",
  "Etouffements",
  "Emphysème (pulmonaire)",
  "Fractures",
  "Douves (Distomatose)",
  "Hépatites",
  "Kyste",
  "Mammite",
  "Ictère",
  "Néphrite",
  "Péricardite",
  "Pétéchie",
  "Péritonite",
  "Pleurésie",
  "Pneumonie",
  "Congestion",
  "Hypertrophie",
  "Tuberculose généralisée",
  "Tuberculose partielle",
  "Cirrhose /tumeur du foie",
  "Septicémie hémorragique",
  "Splénomégalie",
  "Ectoparasitose",
  "Gale",
  "Toux",
  "Traumatisme",
  "Gale",
  "Toux",
];

/** 42 entrées, tableau régional #126. */
export const PRODUITS_SAISIS: string[] = [
  "Abats bovins (Kg)",
  "Bovin entier",
  "Abats chien (Kg)",
  "Abats porc (kg)",
  "Biscuit au lait (boite)",
  "Beurre (boites)",
  "Bonbons au lait (paquet)",
  "Carcasses bovines kg",
  "Carcasse porc (Kg)",
  "Chair de bovins (kg)",
  "Chair de caprins (Kg)",
  "Chair de chien (kg)",
  "Chair de porcins (Kg)",
  "Têtes",
  "Pattes",
  "Foie (Kg)",
  "Poumons",
  "Chair d'ovins (Kg)",
  "Charcuteries (kg)",
  "Crème glacée",
  "Découpes volaille (kg)",
  "Fromage (kg)",
  "Gibier frais (kg)",
  "Gibier fumé (kg)",
  "Lait concentré sucré (boîte)",
  "Lait en poudre (kg)",
  "Lait liquide (L)",
  "Mayonnaise (kg)",
  "Margarine (boite)",
  "Œufs de table (unité)",
  "Mamelle bovine",
  "Poumons bovins",
  "Reins",
  "Poisson en conserve (boite)",
  "Poisson fume (kg)",
  "Poisson frais (Kg)",
  "Poissons congelés (Kg)",
  "Viande porcine (kg)",
  "Viande(t)toutes espèces fraiches",
  "Viande de PR (kg)",
  "Volailles (kg)",
  "Yaourts (boites)",
];

/** 50 entrées, tableau régional #127. */
export const PRODUITS_INSPECTES_MARCHES: string[] = [
  "Aliment en conserve",
  "Beurre (kg)",
  "Cire (kg)",
  "Biscuits au lait((sachet)",
  "Conserves de poisson (kg)",
  "Conserves viandes (bte)",
  "Crème glacée (kg)",
  "Crustacés et mollusques (kg)",
  "Découpes de porc (kg)",
  "Découpes volaille (kg)",
  "Escargots (kg)",
  "Fromage en kg",
  "Gibier frais (kg)",
  "Jambon (kg)",
  "Gibier fumé (kg)",
  "Lait caillé(l)",
  "Lait concentré (bte)",
  "Lait en poudre (kg)",
  "Lait liquide (L)",
  "Mayonnaise (boite)",
  "Miel (L)",
  "Œufs de table (unité)",
  "Peaux et cuirs (kg)",
  "Poisson frais (Kg)",
  "Poisson fumé (kg)",
  "Poisson séché (kg)",
  "Poisson congelé (kg)",
  "Poussins d'un jour",
  "Viande de porc congelée (Kg)",
  "Viande de bœuf (t)",
  "Viande de bœuf fumée (Kg)",
  "Saucisse (kg",
  "Soya (kg)",
  "Viande de petits ruminants (kg)",
  "Viande de porc (kg)",
  "Viande (kg) toutes espèces fraiches",
  "Ecrevisses",
  "Viande de volaille fraîche (kg)",
  "Yaourts (boites)",
  "Tourteau de coton",
  "Tourteau d’arachide",
  "Farine de poisson",
  "Remoulage",
  "Tourteau de palmiste",
  "Volaille",
  "Tourteau de soja",
  "Provende chair(tonne)",
  "Provende porc(tonne)",
  "Provende ponte(tonne)",
  "Aliment poisson (tonne)",
];
